Use cache for Consul queries
allegro/mesos-executor pull request #142
Opened 2021-10-12 14:12 UTC by ojagodzinski

2021-10-12 14:15 UTC, janisz commented
How about spliting it in 3 PRs?

1. Move to go.mod
2. Update deps
3. Use cache for Consul queries

2021-10-12 14:15 UTC, ojagodzinski commented
> How about spliting it in 3 PRs?
> 
> 1. Move to go.mod
> 2. Update deps
> 3. Use cache for Consul queries

long time no see :)

2021-10-14 08:21 UTC, AlfredBroda requested changes

2021-10-14 08:21 UTC, AlfredBroda commented on README.md
> -[![Build Status](https://travis-ci.org/allegro/mesos-executor.svg?branch=master)](https://travis-ci.org/allegro/mesos-executor)
Tutaj można status z akcji CI wyciągnąć - jest taki mały przycisk gdzieś w prawym górnym rogu akcji który kod taki właśnie generuje.

2021-10-14 08:37 UTC, AlfredBroda approved these changes

2021-10-22 13:35 UTC, merged